baseURL = 'https://Z-tianyuan.github.io/'
languageCode = 'zh-cn'
title = 'Z-tianyuan 的技术基地'
theme = 'hugo-book'
buildFuture = true

[params]
  BookSearch = true
  BookSection = '*'
  BookTheme = 'dark'

  BookCustomCSS = ['_custom.scss']

# 下面这三行是关键：允许渲染我们写的名片 HTML 代码！
[markup.goldmark.renderer]
  unsafe = true