baseURL = 'https://Z-tianyuan.github.io/'
languageCode = 'zh-cn'
title = 'Z-tianyuan 的技术基地'
theme = 'hugo-book'

[params]
  BookSearch = true
  BookSection = '*'
  # 这行是重点：强制开启极客暗黑模式！
  BookTheme = 'dark'
